### ISSUE TITLE
[SUGGESTION] Upload artifact after build

### ISSUE THREAD

**Issue by Sneakometer** [Earthcomputer/multiconnect#267]
Since multiconnect already uses github actions, I suggest adding and extra step at the end to publish the artifact.
With this, everyone can download latest builds without waiting for a new release or cloning and building it by themself.

Suggested addition to the build.yml:
```
    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: multiconnect
        path: build/libs/*.jar
```
